config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'signout', to: 'sessions#destroy', as: 'signout'

   resources :sessions, only: [:create, :destroy]
   resource :home, only: [:show]

 get "reports/generate_report" => "reports#generate_report"
 get "/personas/export" => "personas#export"
 get "/personas/import" => "personas#import"
 post "/personas/import" => "personas#importar"
 get "/reports/template" => "reports#template"
 get "/personas/update_cantones", as: "update_cantones"
 get "/personas/update_distritos", as: "update_distritos"
 get "/personas/update_tipos_padecimientos", as: "update_tipos_padecimientos"
 get "/reports/update_cantones_report", as: "update_cantones_report"
 get "/reports/update_distritos_report", as: "update_distritos_report"
 get "/reports/update_tipos_padecimientos_report", as: "update_tipos_padecimientos_report"
  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resources :reports
  resources :lookups
  resources :personas do
    resources :info_contactos
    resources :info_extra_pacientes
    resources :diagnosticos
    resources :historial_clinicos
    resources :direccions
  end

  root 'personas#index'

end

app/models/info_contacto.rb
class InfoContacto < ActiveRecord::Base
		belongs_to :persona,
				   :foreign_key => "persona_id"
end

app/controllers/info_contactos_controller.rb
class InfoContactosController < ApplicationController
  before_action :set_info_contacto, only: [:show, :edit, :update, :destroy]

  # GET /info_contactos
  # GET /info_contactos.json
  def index
    @persona = Persona.find(params[:persona_id])
    @info_contacto = @persona.info_contactos.all
    format.html { render :show }
  end

  # GET /info_contactos/1
  # GET /info_contactos/1.json
  def show
  end

  # GET /info_contactos/new
  def new
    @info_contacto = InfoContacto.new
  end

  # GET /info_contactos/1/edit
  def edit
  end

  # POST /info_contactos
  # POST /info_contactos.json
  def create
    @persona = Persona.find(params[:persona_id])
    @info_contacto = @persona.info_contactos.new(info_contacto_params)
    respond_to do |format|
      if @info_contacto.save
        format.html { redirect_to @persona, notice: 'Info contacto was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_contactos/1
  # PATCH/PUT /info_contactos/1.json
  def update
    @persona = Persona.find(params[:persona_id])
    respond_to do |format|
      if @persona.info_contacto.update(info_contacto_params)
        format.html { redirect_to @info_contacto, notice: 'Info contacto was successfully updated.' }
        format.json { render :show, status: :ok, location: @info_contacto }
      else
        format.html { render :edit }
        format.json { render json: @info_contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_contactos/1
  # DELETE /info_contactos/1.json
  def destroy
    @persona = Persona.find(params[:persona_id])
    @info_contacto = @persona.info_contactos.find(params[:id])
    @info_contacto.destroy
    respond_to do |format|
      format.html { redirect_to @persona, notice: 'Contacto Eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info_contacto
      @info_contacto = InfoContacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_contacto_params
      params.require(:info_contacto).permit(:telefono, :nombre_contacto, :parentesco, :fk_id_paciente)
    end
end

app/helpers/info_contactos_helper.rb
module InfoContactosHelper
end

app/views/info_contactos/_form.html.erb
<%= form_for([@persona, @persona.info_contactos.build]) do |f|%>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this info_contacto from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :nombre_contacto %><br>
    <%= f.text_field :nombre_contacto %>
  </div>
  <div class="field">
    <%= f.label :parentesco %><br>
    <%= f.text_field :parentesco %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-default" %>
  </div>

<% end %>

app/views/info_contactos/_info_contacto.html.erb
      <tr>
        <td><%= best_in_place info_contacto.persona, :telefono %></td>
        <td><%= info_contacto.nombre_contacto %></td>
        <td><%= info_contacto.parentesco %></td>
        <td><%= link_to [info_contacto.persona, info_contacto], method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash"></i>
        <% end %> </td>
      </tr>

app/views/info_contactos/edit.html.erb
<h1>Modificar Informacion General</h1>

<%= render 'form' %>

<%= link_to 'Show', @info_contacto %> |
<%= link_to 'Back', info_contactos_path %>

app/views/info_contactos/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to 'Información Personal', new_persona_path %></li>
  <li role="presentation" class="active" ><%= link_to 'Información - Contactos', info_contactos_path %></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>

<p id="notice"><%= notice %></p>
<table class="table table-hover table-condensed table-striped" height="75%">
  <thead>
    <tr>
      <th>Telefono</th>
      <th>Nombre contacto</th>
      <th>Parentesco</th>
      <th>Fk id paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= @persona.info_contactos.each do |f| %>
      <tr>
        <td><%= f.telefono %></td>
        <td><%= f.nombre_contacto %></td>
        <td><%= f.parentesco %></td>
        <td><%= link_to 'Show', info_contacto %></td>
        <td><%= link_to 'Edit', edit_info_contacto_path(info_contacto) %></td>
        <td><%= link_to 'Destroy', info_contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info contacto', new_info_contacto_path %>

app/views/info_contactos/new.html.erb
<% @persona %>
<%= render 'form' %>


<%= link_to 'Atras', persona_path %>

app/views/info_contactos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Telefono:</strong>
  <%= @info_contacto.telefono %>
</p>

<p>
  <strong>Nombre contacto:</strong>
  <%= @info_contacto.nombre_contacto %>
</p>

<p>
  <strong>Parentesco:</strong>
  <%= @info_contacto.parentesco %>
</p>

<%= link_to edit_info_contacto_path(@info_contacto), class: "btn btn-warning" do %>
    <i class="fa fa-pencil">Editar Paciente</i>
<% end %>
<%= link_to 'Back', info_contactos_path %>