config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'signout', to: 'sessions#destroy', as: 'signout'

   resources :sessions, only: [:create, :destroy]
   resource :home, only: [:show]

 get "reports/generate_report" => "reports#generate_report"
 get "/personas/export" => "personas#export"
 get "/personas/import" => "personas#import"
 post "/personas/import" => "personas#importar"
 get "/reports/template" => "reports#template"
 get "/personas/update_cantones", as: "update_cantones"
 get "/personas/update_distritos", as: "update_distritos"
 get "/personas/update_tipos_padecimientos", as: "update_tipos_padecimientos"
 get "/reports/update_cantones_report", as: "update_cantones_report"
 get "/reports/update_distritos_report", as: "update_distritos_report"
 get "/reports/update_tipos_padecimientos_report", as: "update_tipos_padecimientos_report"
  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resources :reports
  resources :lookups
  resources :personas do
    resources :info_contactos
    resources :info_extra_pacientes
    resources :diagnosticos
    resources :historial_clinicos
    resources :direccions
  end

  root 'personas#index'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_many :info_contactos
	has_many :direccions
	has_many :info_extra_pacientes
	has_many :historial_clinicos
	has_many :diagnosticos
	accepts_nested_attributes_for :info_extra_pacientes
	validates :cedula, length: { maximum: 9, message: "debe ser de 9 digitos"}
  validates :telefono, length: { maximum: 8, message: "debe ser de 8 digitos"}
end

app/controllers/personas_controller.rb
require 'spreadsheet'
require 'spreadsheet/excel'

class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  # GET /personas
  # GET /personas.json
  # def show
  #   @city = City.find_by("id = ?", params[:trip][:city_id])
  # end
  #
  # def update_cities
  #   @cities = City.where("country_id = ?", params[:country_id])
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @provincias = Lookup.where("descripcion = ?", "Provincia")
    @cantones = Lookup.where("descripcion = ?", "Canton - #{@provincias.first.value}")
    puts "cantones #{@cantones}"
    @distritos = Lookup.where("descripcion = ?", "Distrito - #{@cantones.first.value}")
    @padecimientos = Lookup.where("descripcion = ?", "Padecimiento")
    @tipos_padecimientos = Lookup.where("descripcion = ?", "Padecimiento - #{@padecimientos.first.value}")
  end

  def update_cantones
    provincia = Lookup.where("id = ? ", params[:provincia_id]).as_json
    @cantones = Lookup.where("descripcion = ? ", "Canton - #{provincia[0]['value']}") #.collect { |m| [m.value, m.id] }
    respond_to do |format|
      format.js
    end
  end

  def update_distritos
    canton = Lookup.where("id = ? ", params[:canton_id]).as_json
    @distritos = Lookup.where("descripcion = ? ", "Distrito - #{canton[0]['value']}") #.collect { |m| [m.value, m.id] }
    respond_to do |format|
      format.js
    end
  end

  def update_tipos_padecimientos
    padecimiento = Lookup.where("id = ? ", params[:padecimiento_id]).as_json
    @tipos_padecimientos = Lookup.where("descripcion = ? ", "Padecimiento - #{padecimiento[0]['value']}") #.collect { |m| [m.value, m.id] }
    puts " tipos #{@tipos_padecimientos.inspect}"
    respond_to do |format|
      format.js
    end
  end
  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)
    # If Genero False = femenino
    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Informacion guardada correctamente.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        # @persona.build_info_extra_paciente
        format.html { redirect_to @persona, notice: 'Informacion actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def importar
    @file = params[:file]
    book = Spreadsheet.open @file.tempfile.to_path.to_s
    # '/Users/paolacalderon/Documents/ProyectoDaniel/importar-pacientes.xls'
    sheet1 = book.worksheet 0
    sheet1.each 1 do |row|
      @persona = Persona.new
      @persona.nombre = row[0]
      @persona.primer_apellido = row[1]
      @persona.segundo_apellido = row[2]
      @persona.cedula = row[3]
      @persona.telefono = row[4]
      @persona.save
     end
    redirect_to personas_url
  end

  def export()
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name = 'Informacion Pacientes'
    sheet2 = book.create_worksheet
    sheet3 = book.create_worksheet
    sheet4 = book.create_worksheet
    sheet5 = book.create_worksheet
    sheet6 = book.create_worksheet
    sheet2.name = 'Informacion Contactos'
    sheet3.name = 'Informacion Extra'
    sheet4.name = 'Direccion'
    sheet5.name = 'Diagnostico'
    sheet6.name = 'Historial Medico'
    sheet1.row(0).concat %w{Nombre PrimerApellido SegundoApellido Cedula Telefono}
    sheet2.row(0).concat %w{Nombre Contacto Parentesco Telefono}
    sheet3.row(0).concat %w{Nombre Estudia Trabaja LugarEstudioTrabajo TieneHijos CantidadHijos ReferenciaTrabajoSocial AyudaAlimentos AyudaMedicamento}
    sheet4.row(0).concat %w{Nombre Provincia Canton Distrito DireccionExacta}
    sheet5.row(0).concat %w{Nombre Fecha Especialidad Padecimiento TipoPadecimiento Hospital Descripcion}
    sheet6.row(0).concat %w{Nombre Fecha EstadoActual}
    @personas = Persona.all
    i=1
    l=1
    l1 =1;
    l2 =1;
    l3 =1;
    l4 =1;
    @personas.each do |p|
      sheet1.row(i).push p.nombre, p.primer_apellido, p.segundo_apellido, p.cedula.nil? ? " ":p.cedula, p.telefono.nil? ? " ":p.telefono
      i=i+1
      nombre = p.nombre + " " + p.primer_apellido + " " + p.segundo_apellido
      p.info_contactos.each do |ic|
        l=l+1
        sheet2.row(l).push nombre, ic.nombre_contacto.nil? ? " ": ic.nombre_contacto, ic.parentesco.nil? ? " ":ic.parentesco, ic.telefono.nil? ? " ":ic.telefono
      end
      p.info_extra_pacientes.each do |ic|
        l1=l1+1
        sheet3.row(l1).push nombre, ic.estudiante ? "Si" : "No", ic.trabajador ? "Si" : "No",
                           ic.lugar_estudio_trabajo.nil? ? " ": ic.lugar_estudio_trabajo,
                           ic.hijos ? "Si" : "No",
                           ic.cant_hijos.nil? ? " ": ic.cant_hijos,
                           ic.referencia_trab_social ? "Si" : "No",
                           ic.ayuda_alimentos ? "Si" : "No",
                           ic.ayuda_medicamento ? "Si" : "No"
      end
      p.direccions.each do |ic|
        l2=l2+1
        sheet4.row(l2).push nombre, ic.provincia.nil? ? " ": id_to_value_direccion(ic.provincia),
                           ic.canton.nil? ? " ": id_to_value_direccion(ic.canton),
                           ic.distrito.nil? ? " ": id_to_value_direccion(ic.distrito),
                           ic.direccion_exacta.nil? ? " ": ic.direccion_exacta
      end
      p.diagnosticos.each do |ic|
        l3=l3+1
        sheet5.row(l3).push nombre, ic.fecha.nil? ? " ": ic.fecha.strftime("%d-%m-%Y") ,
                           ic.especialidad_id.nil? ? " ": id_to_value_direccion(ic.especialidad_id),
                           ic.padecimiento.nil? ? " ": id_to_value_direccion(ic.padecimiento),
                           ic.tipo_padecimiento.nil? ? " ": id_to_value_direccion(ic.tipo_padecimiento),
                           ic.hospital.nil? ? " ": id_to_value_direccion(ic.hospital),
                           ic.description.nil? ? " ": ic.description
      end
      p.historial_clinicos.each do |ic|
        l4=l4+1
        sheet6.row(l4).push nombre, ic.fecha.nil? ? " ": ic.fecha.strftime("%d-%m-%Y") ,
                           ic.fk_id_lookup.nil? ? " ": id_to_value_direccion(ic.fk_id_lookup)
      end
    end
    # sheet1[1,0] = 'Japan'
    # row = sheet1.row(1)
    # row.push 'Creator of Ruby'
    # row.unshift 'Yukihiro Matsumoto'
    # sheet1.row(2).replace [ 'Daniel J. Berger', 'U.S.A.',
    #                         'Author of original code for Spreadsheet::Excel' ]
    # sheet1.row(3).push 'Charles Lowe', 'Author of the ruby-ole Library'
    # sheet1.row(3).insert 1, 'Unknown'
    # sheet1.update_row 4, 'Hannes Wyss', 'Switzerland', 'Author'

    sheet1.row(0).height = 18

    format = Spreadsheet::Format.new :color => :blue,
                                     :weight => :bold,
                                     :size => 18
    sheet1.row(0).default_format = format

    bold = Spreadsheet::Format.new :weight => :bold
    4.times do |x| sheet1.row(x + 1).set_format(0, bold) end
    # book.write '/Users/paolacalderon/Documents/ProyectoDaniel/excel-pacientes.xls'
    t = Time.now.strftime('%v %r')
    book.write "excel-pacientes-#{t}.xls"
    send_file "excel-pacientes-#{t}.xls", :type=>"application/excel", :filename => "excel-pacientes-#{t}.xls", :stream => false
    #redirect_to personas_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :primer_apellido, :segundo_apellido, :fecha_nacimiento, :correo_electronico, :genero, :cedula, :estado_civil, :telefono)
    end

    def id_to_value_direccion(id)
      return Lookup.where(id: id).first.value
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
  def get_estados_civiles()
      Lookup.where(lookup_type: 'EstadoCivil').collect { |m| [m.value, m.id] }
  end

  def field_class(resource, field_name)
    if resource.errors[field_name]
      return "error".html_safe
    else
      return "form-control".html_safe
    end
  end
end

app/views/personas/_canton.js.erb
$('#canton').html(<%= options_from_collection_for_select(@cantones, :id, :value) %>);

app/views/personas/_distrito.js.erb
$('#distrito').html(<%= options_from_collection_for_select(@distritos, :id, :value) %>);

app/views/personas/_form.html.erb
<%= bootstrap_form_for(@persona, inline_errors: true) do |f| %>
      <div class="form-group">
          <%= f.text_field :nombre, id:"nombre1", class:"form-control", size:"20", placeholder:"Nombre"  %>
      </div>
      <div class="form-group">
          <%= f.text_field :primer_apellido, id:"primer_apellido2", class:"form-control", size:"20", placeholder:"Primer Apellido" %>
      </div>
      <div class="form-group">
          <%= f.text_field :segundo_apellido, id:"segundo_apellido3", class:"form-control", size:"20", placeholder:"Segundo Apellido" %>
      </div>
      <div class="form-group">
        <%= f.text_field :fecha_nacimiento, id:"fn4", class:"form-control", 'data-behaviour' => 'datepicker' %>
      </div>
      <div class="form-group">
        <%= f.text_field :correo_electronico, id:"email", class:"form-control", size:"20", placeholder:"correo@dominio.com" %>
      </div>
      <div class="form-group">
          <%= f.select(:genero, [['Masculino', '1'], ['Femenino', '0']],id:'genero1') %>
      </div>
      <div class="form-group">
          <%= f.text_field :cedula, id:"cedula", class: field_class(@persona, :cedula) , size:"20s", placeholder:"XXXXXXXXX" %>
      </div>
      <div class="form-group">
          <%= f.select(:estado_civil, get_estados_civiles(), id:'estado_civil') %>
      </div>
      <div class="form-group">
          <%= f.text_field :telefono, class: field_class(@persona, :telefono), size:"20" %>
      </div>
      <div class="form-group">
        <%= f.submit "Guardar Informacion", class: "btn btn-default" do %>
            <i class="fa fa-floppy-o"></i>
        <% end %>
      </div>

<% end %>

app/views/personas/_list.html.erb
<%= form_for([@persona, @persona.info_contactos.build]) do |f|%>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this info_contacto from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :nombre_contacto %><br>
    <%= f.text_field :nombre_contacto %>
  </div>
  <div class="field">
    <%= f.label :parentesco %><br>
    <%= f.text_field :parentesco %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-default" %>
  </div>

<% end %>

app/views/personas/_tipo_padecimiento.js.erb
$('#tipo_padecimiento').html(<%= options_from_collection_for_select(@tipos_padecimientos, :id, :value) %>);

app/views/personas/edit.html.erb
<h1>Informacion General - Edicion</h1>

<%= render 'form' %>

app/views/personas/import.html.erb
<h2>Importar Excel - Pacientes</h2>
<%= form_tag personas_import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar" %>
<% end %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>


<div class="page-header">
  <h1>Lista de Pacientes</h1>
</div>
  <table id="pacientes_table" class="table table-hover table-condensed table-striped" height="30%" width="50%">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Primer apellido</th>
        <th>Segundo apellido</th>
        <th>Fecha nacimiento</th>
        <th>Correo electronico</th>
        <th>Telefono</th>
        <th colspan="3">Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @personas.each do |persona| %>
        <tr>
          <td><%= persona.nombre %></td>
          <td><%= persona.primer_apellido %></td>
          <td><%= persona.segundo_apellido %></td>
          <td><%= persona.fecha_nacimiento.nil? ? " ":persona.fecha_nacimiento.strftime("%d-%m-%Y") %></td>
          <td><%= persona.correo_electronico %></td>
          <td><%= persona.telefono %></td>
          <td><%= link_to persona do %>
            <i class="fa fa-eye"></i>
          <% end %> </td>
          <td><%= link_to edit_persona_path(persona) do %>
            <i class="fa fa-pencil"></i>
          <% end %> </td>
          <td><%= link_to persona, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
          <% end %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to new_persona_path, class: "btn btn-default" do %>
    <i class="fa fa-plus">Agregar Paciente</i>
<% end %> |
<%= link_to personas_export_path, class: "btn btn-default" do %>
    <i class="fa fa-plus">Exportar Paciente</i>
<% end %>

app/views/personas/new.html.erb
<%= render 'form' %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Expediente: <%= @persona.nombre %> <%= @persona.primer_apellido %> <%= @persona.segundo_apellido %></h1>


<h2>Información General</h2>


<table class="table table-hover table-condensed table-striped"  height="5%" width="50%">
  <thead>
    <tr>
      <th>Fecha Nacimiento</th>
      <th>Correo Electronico</th>
      <th>Genero</th>
      <th>Cedula</th>
      <th>Estado Civil</th>
      <th>Telefono</th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td><%= @persona.fecha_nacimiento.strftime("%d/%m/%Y") %></td>
        <td><%= best_in_place @persona, :correo_electronico %></td>
        <td><%= @persona.genero == false ? "Femenino":"Masculino" %></td>
        <td><%= @persona.cedula %></td>
        <td><%= case @persona.estado_civil
            when 1
              @persona.genero == false ? "Soltera": "Soltero"
            when 2
              @persona.genero == false ? "Casada": "Casado"
            when 3
              "Union Libre"
            else
              @persona.genero == false ? "Viuda": "Viudo"
            end
         %></td>
         <td><%= @persona.telefono %></td>
      </tr>
  </tbody>
</table>
<%= link_to edit_persona_path(@persona), class: "btn btn-default" do %>
    <i class="fa fa-pencil">Editar Paciente</i>
<% end %>


<!-- INFORMACION CONTACTOS -->
<h2>Informacion Contacto</h2>
<table class="table table-hover table-condensed table-striped" height="5%" width="30%">
  <thead>
    <tr>
      <th>Telefono</th>
      <th>Nombre contacto</th>
      <th>Parentesco</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <%= render @persona.info_contactos%>
</tbody>
</table>

<%= link_to new_persona_info_contacto_path(@persona),class: "btn btn-default", id: "btnContacto", onclick: "javascript:showhide('uniquename')" ,remote: true do %>
    <i class="fa fa-plus">Agregar Contacto</i>
<% end %>
<div id="uniquename" style="display:none;">
  <%= render "info_contactos/form" %>
</div>

<!-- FIN INFORMACION CONTACTOS -->

<!-- INFORMACION EXTRA -->
<h2>Informacion Extra del Paciente</h2>
<table class="table table-hover table-condensed table-striped" height="5%" width="30%">
  <thead>
    <tr>
      <th>Estudiante</th>
      <th>Trabajador</th>
      <th>Lugar estudio trabajo</th>
      <th>Hijos</th>
      <th>Cant hijos</th>
      <th>Cant Hermanos</th>
      <th>Referencia trab social</th>
      <th>Ayuda alimentos</th>
      <th>Ayuda medicamento</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>
  <tbody>
  <% if @persona.info_extra_pacientes.size == 0 || @persona.info_extra_pacientes.nil? %>
      <tr><td colspan="8"> No existe informacion relacionada</td>
      <tr><%= render "info_extra_pacientes/form" %></tr>
  </tbody>
</table>
<% else %>
    <%= render @persona.info_extra_pacientes %>
      </tbody>
    </table>
  <% end %>
<!-- FIN INFORMACION EXTRA -->

<!-- DIRECCIONES -->
<h2>Direccion</h2>
<table class="table table-hover table-condensed table-striped" height="5%" width="30%">
  <thead>
    <tr>
      <th>Provincia</th>
      <th>Canton</th>
      <th>Distrito</th>
      <th>Direccion exacta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @persona.direccions.nil? || @persona.direccions.size == 0 %>
        <tr><td colspan="11"> No existen direcciones para <%= @persona.nombre %></td><tr>
        <tr><%= render "direccions/form" %></tr>
        </tbody>
      </table>
    <% else %>
      <%= render @persona.direccions %>
        </tbody>
      </table>
    <% end %>

<!-- FIN DIRECCIONES -->

<!-- DIAGNOSTICO -->
<h2>Diagnostico</h2>
<table class="table table-hover table-condensed table-striped" height="5%" width="30%">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Especialidad</th>
      <th>Padecimiento</th>
      <th>Tipo Padecimiento</th>
      <th>Hospital</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr><%= render @persona.diagnosticos %></tr>
      <tr><%= render "diagnosticos/form" %></tr>
    </tbody>
  </table>
<!-- FIN DIAGNOSTICO -->


<!-- HISTORIAL CLINICO -->
<h2>Historial Clinico</h2>
<table class="table table-hover table-condensed table-striped" height="5%" width="30%">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado Actual</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <%= render @persona.historial_clinicos%>
  <div id="historial" style="display:none;">
        <%= render "historial_clinicos/form" %>
  </div>
</tbody>
</table>
<!-- <%= link_to new_persona_historial_clinico_path(@persona),class: "btn btn-default", id: "btnContacto", onclick: "javascript:showhide('historial')" ,remote: true do %>
    <i class="fa fa-plus">Agregar Estado del Paciente</i>
<% end %> -->


<!-- FIN HISTORIAL CLINICO-->
    <br><br><br><br>
  <%= link_to personas_path, class: "btn btn-default" do %>
        <i class="fa fa-undo">Atras</i>
    <% end %>

app/views/personas/update_tipos_padecimientos.js.erb
$("#tipo_padecimiento_select").empty()
  .append("<%= escape_javascript(render(:partial => 'tipo_padecimiento')) %>")