config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'signout', to: 'sessions#destroy', as: 'signout'

   resources :sessions, only: [:create, :destroy]
   resource :home, only: [:show]

 get "reports/generate_report" => "reports#generate_report"
 get "/personas/export" => "personas#export"
 get "/personas/import" => "personas#import"
 post "/personas/import" => "personas#importar"
 get "/reports/template" => "reports#template"
 get "/personas/update_cantones", as: "update_cantones"
 get "/personas/update_distritos", as: "update_distritos"
 get "/personas/update_tipos_padecimientos", as: "update_tipos_padecimientos"
 get "/reports/update_cantones_report", as: "update_cantones_report"
 get "/reports/update_distritos_report", as: "update_distritos_report"
 get "/reports/update_tipos_padecimientos_report", as: "update_tipos_padecimientos_report"
  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resources :reports
  resources :lookups
  resources :personas do
    resources :info_contactos
    resources :info_extra_pacientes
    resources :diagnosticos
    resources :historial_clinicos
    resources :direccions
  end

  root 'personas#index'

end

app/models/info_extra_paciente.rb
class InfoExtraPaciente < ActiveRecord::Base
		belongs_to :persona,
				   :foreign_key => "persona_id"
end

app/controllers/info_extra_pacientes_controller.rb
class InfoExtraPacientesController < ApplicationController
  before_action :set_info_extra_paciente, only: [:show, :edit, :update, :destroy]

  # GET /info_extra_pacientes
  # GET /info_extra_pacientes.json
  def index
    @persona = Persona.find(params[:persona_id])
    @info_extra_paciente = @persona.info_extra_pacientes.all
    format.html { render :show }
  end

  # GET /info_extra_pacientes/1
  # GET /info_extra_pacientes/1.json
  def show
  end

  # GET /info_extra_pacientes/new
  def new
    @info_extra_paciente = InfoExtraPaciente.new
  end

  # GET /info_extra_pacientes/1/edit
  def edit
  end

  # POST /info_extra_pacientes
  # POST /info_extra_pacientes.json
  def create
    @persona = Persona.find(params[:persona_id])
    @info_extra_paciente = @persona.info_extra_pacientes.new(info_extra_paciente_params)
    respond_to do |format|
      if @info_extra_paciente.save
        format.html { redirect_to @persona, notice: 'Informacion de Contacto agregada.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_extra_pacientes/1
  # PATCH/PUT /info_extra_pacientes/1.json
  def update
    @persona = Persona.find(params[:persona_id])
    respond_to do |format|
      if @persona.info_extra_pacientes.update(info_extra_paciente_params)
        format.html { redirect_to @info_extra_paciente, notice: 'Info extra actualizada.' }
        format.json { render :show, status: :ok, location: @info_extra_paciente }
      else
        format.html { render :edit }
        format.json { render json: @info_extra_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_extra_pacientes/1
  # DELETE /info_extra_pacientes/1.json
  def destroy
    @persona = Persona.find(params[:persona_id])
    @info_extra_paciente = @persona.info_extra_pacientes.find(params[:id])
    @info_extra_paciente.destroy
    respond_to do |format|
      format.html { redirect_to @persona, notice: 'Contacto Eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info_extra_paciente
      @info_extra_paciente = InfoExtraPaciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_extra_paciente_params
      params.require(:info_extra_paciente).permit(:estudiante, :trabajador, :lugar_estudio_trabajo, :hijos, :cant_hijos, :referencia_trab_social, :ayuda_alimentos, :ayuda_medicamento, :fk_id_persona)
    end
end

app/helpers/info_extra_pacientes_helper.rb
module InfoExtraPacientesHelper
end

app/views/info_extra_pacientes/_form.html.erb
<%= form_for([@persona, @persona.info_extra_pacientes.build]) do |f|%>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this info_extra_paciente from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <td><%= f.check_box :estudiante %></td>
      <td><%= f.check_box :trabajador %></td>
      <td><%= f.text_field :lugar_estudio_trabajo %></td>
      <td><%= f.check_box :hijos %></td>
      <td><%= f.number_field :cant_hijos %></td>
      <td><%= f.number_field :cant_hermanos %></td>
      <td><%= f.check_box :referencia_trab_social %></td>
      <td><%= f.check_box :ayuda_alimentos %></td>
      <td><%= f.check_box :ayuda_medicamento %></td>
      <td><%= f.submit 'Guardar', class: "btn btn-primary"%></td>
<% end %>

app/views/info_extra_pacientes/_info_extra_paciente.html.erb
<tr>
  <td><%= info_extra_paciente.estudiante ? "Si": "No"%>
  <td><%= info_extra_paciente.trabajador ? "Si": "No"%>
  <td><%= info_extra_paciente.lugar_estudio_trabajo%>
  <td><%= info_extra_paciente.hijos ? "Si": "No" %></td>
  <td><%= info_extra_paciente.cant_hijos.nil? ? "0": info_extra_paciente.cant_hijos %></td>
  <td><%= info_extra_paciente.cant_hermanos.nil? ? "0": info_extra_paciente.cant_hermanos %></td>
  <td><%= info_extra_paciente.referencia_trab_social ? "Si": "No"  %></td>
  <td><%= info_extra_paciente.ayuda_alimentos ? "Si": "No"  %></td>
  <td><%= info_extra_paciente.ayuda_medicamento ? "Si": "No"  %></td>
  <td><%= link_to [info_extra_paciente.persona, info_extra_paciente], method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="fa fa-trash"></i>
  <% end %> </td>
</tr>

app/views/info_extra_pacientes/edit.html.erb
<h1>Editing Info Extra Paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @info_extra_paciente %> |
<%= link_to 'Back', info_extra_pacientes_path %>

app/views/info_extra_pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Info Extra Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Estudiante</th>
      <th>Trabajador</th>
      <th>Lugar estudio trabajo</th>
      <th>Hijos</th>
      <th>Cant hijos</th>
      <th>Referencia trab social</th>
      <th>Ayuda alimentos</th>
      <th>Ayuda medicamento</th>
      <th>Fk id persona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @persona.info_extra_paciente.estudiante %></td>
        <td><%= @persona.info_extra_paciente.trabajador %></td>
        <td><%= @persona.info_extra_paciente.lugar_estudio_trabajo %></td>
        <td><%= @persona.info_extra_paciente.hijos %></td>
        <td><%= @persona.info_extra_paciente.cant_hijos %></td>
        <td><%= @persona.info_extra_paciente.cant_hermanos %></td>
        <td><%= @persona.info_extra_paciente.referencia_trab_social %></td>
        <td><%= @persona.info_extra_paciente.ayuda_alimentos %></td>
        <td><%= @persona.info_extra_paciente.ayuda_medicamento %></td>
        <td><%= @persona.info_extra_paciente.persona_id %></td>
        <td><%= @persona.link_to 'Destroy', persona_info_extra_paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Info extra paciente', new_info_extra_paciente_path %>

app/views/info_extra_pacientes/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', persona_info_extra_pacientes_path %>

app/views/info_extra_pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estudiante:</strong>
  <%= @info_extra_paciente.estudiante %>
</p>

<p>
  <strong>Trabajador:</strong>
  <%= @info_extra_paciente.trabajador %>
</p>

<p>
  <strong>Lugar estudio trabajo:</strong>
  <%= @info_extra_paciente.lugar_estudio_trabajo %>
</p>

<p>
  <strong>Hijos:</strong>
  <%= @info_extra_paciente.hijos %>
</p>

<p>
  <strong>Cant hijos:</strong>
  <%= @info_extra_paciente.cant_hijos %>
</p>

<p>
  <strong>Referencia trab social:</strong>
  <%= @info_extra_paciente.referencia_trab_social %>
</p>

<p>
  <strong>Ayuda alimentos:</strong>
  <%= @info_extra_paciente.ayuda_alimentos %>
</p>

<p>
  <strong>Ayuda medicamento:</strong>
  <%= @info_extra_paciente.ayuda_medicamento %>
</p>

<p>
  <strong>Fk id persona:</strong>
  <%= @info_extra_paciente.fk_id_persona %>
</p>

<%= link_to 'Edit', edit_info_extra_paciente_path(@info_extra_paciente) %> |
<%= link_to 'Back', info_extra_pacientes_path %>