config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'signout', to: 'sessions#destroy', as: 'signout'

   resources :sessions, only: [:create, :destroy]
   resource :home, only: [:show]

 get "reports/generate_report" => "reports#generate_report"
 get "/personas/export" => "personas#export"
 get "/personas/import" => "personas#import"
 post "/personas/import" => "personas#importar"
 get "/reports/template" => "reports#template"
 get "/personas/update_cantones", as: "update_cantones"
 get "/personas/update_distritos", as: "update_distritos"
 get "/personas/update_tipos_padecimientos", as: "update_tipos_padecimientos"
 get "/reports/update_cantones_report", as: "update_cantones_report"
 get "/reports/update_distritos_report", as: "update_distritos_report"
 get "/reports/update_tipos_padecimientos_report", as: "update_tipos_padecimientos_report"
  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resources :reports
  resources :lookups
  resources :personas do
    resources :info_contactos
    resources :info_extra_pacientes
    resources :diagnosticos
    resources :historial_clinicos
    resources :direccions
  end

  root 'personas#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PacientesAdminBootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'menu'%>

  <%= csrf_meta_tags %>
</head>
<body>


<div class="background-orange">
    <div class="wrap">
      <nav class="nav-bar navbar-inverse header" role="navigation">
          <div id ="top-menu" class="container-fluid active header">
              <!-- a class="navbar-brand" href="/"> -->
                <%= link_to image_tag('logo2_104.jpg', class:'logo'), {action: 'index', controller: 'personas'}, {class: 'navbar-brand'} %>
                <br/>
                <br/>
              <ul class="nav navbar-nav">

                  <li class="dropdown movable">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret"></span><span class="fa fa-4x fa-child"></span></a>
                      <ul class="dropdown-menu" role="menu">


                          <% if !current_user %>
                          <li>
                            <%= link_to "/auth/google_oauth2", id: "sign_in" do %>
                                <i class="fa fa-user"><span class="tab">Ingresar</span></i>
                            <% end %>
                          <li class="divider"></li>
                          <% else %>
                            <span>
                              Usuario: <strong><%= current_user.name %></strong>
                              <%# [START logout] %>
                              <li><%= link_to signout_path do %>
                                  <i class="fa fa-power-off"><span class="tab">Salir</span></i>
                              <% end %>
                            </span>
                          <% end %>
                      </ul>
                  </li>
                  <li>
                    <p class="navbar-text navbar-right">
</p>
                  </li>

              </ul>
          </div>
      </nav>
      <aside id="side-menu" class="aside" role="navigation">
            <ul class="nav nav-list accordion">

              <li class="nav-header">
                <div class="link"><i class="fa fa-lg fa-users"></i>Pacientes<i class="fa fa-chevron-down"></i></div>
                <ul class="submenu">
                  <li><%= link_to "Agregar Paciente", new_persona_path %></li>
                  <li><%= link_to "Mostrar Paciente", personas_path %></li>
                  <li><%= link_to "Importar Paciente", personas_import_path %></li>
                </ul>
              </li>

              <li class="nav-header">
                <div class="link"><i class="fa fa-file-text-o"></i>Documentos<i class="fa fa-chevron-down"></i></div>
                <ul class="submenu">
                  <li><%= link_to "Plantilla - Importar", reports_template_path %></li>
                </ul>
              </li>

              <li class="nav-header">
                <div class="link"><i class="fa fa-lg fa-bar-chart"></i>Reportes<i class="fa fa-chevron-down"></i></div>
                <ul class="submenu">
                  <li><%= link_to "Generar", reports_path %> </li>
                </ul>
              </li>
              <li class="nav-header">
                <div class="link"><i class="fa fa-lg fa-cog"></i>Configuracion<i class="fa fa-chevron-down"></i></div>
                <ul class="submenu">
                  <li><a href="#">Usuarios</a></li>
                  <li><%= link_to "Direcciones", lookups_path(@lookup, :lookup_type => "Direcciones") %> </li>
                  <li><%=link_to "Especialidades Medicas", lookups_path(@lookup, :lookup_type => "Especialidades") %> </li>
                  <li><%= link_to "Padecimientos" , lookups_path(@lookup, :lookup_type => "Padecimientos") %></li>
                  <li><%= link_to "Estados Paciente", lookups_path(@lookup, :lookup_type => "Estados Paciente") %></li>
                  <li><%= link_to "Hospitales", lookups_path(@lookup, :lookup_type => "Hospitales") %></li>
                  <li><%= link_to "Tipo de Atencion", lookups_path(@lookup, :lookup_type => "Tipo de Atencion") %></li>
                  <li><%= link_to "Estado Civil", lookups_path(@lookup, :lookup_type => "Estado Civil") %></li>
                </ul>
              </li>

          </ul>
      </aside>

      <!--Body content-->
      <div class="content">
        <div class="top-bar">
          <a href="#menu" class="side-menu-link burger">
            <span class='burger_inside' id='bgrOne'></span>
            <span class='burger_inside' id='bgrTwo'></span>
            <span class='burger_inside' id='bgrThree'></span>
          </a>
        </div>
        <section class="content-inner">
          <p><%= yield %></p>
        </section>
      </div>
    </div>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" %>
</body>
</html>

app/views/layouts/current_user.json.erb
[
  <% session[:usuario].each do |user| %>
    { 'image_url': <%= user.image_url %>, 'name': "<%= hotel.name %>" },
  <% end %>
]